version: "3.2"
services:
  app:
    build:
        context: ./rest-api
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - CHAOS_MONKEY_ENABLED=false
      - CHAOS_MONKEY_MODE=critical
      - CHAOS_MONKEY_LATENCY=false
      - CHAOS_MONKEY_EXCEPTION=false
      - CHAOS_MONKEY_APP_KILLER=false
      - CHAOS_MONKEY_MEMORY=false
      - AWS_REGION=us-east-1
      - DYNAMO_SALES_TABLE=sales
    ports:
        - 8080:8080
    volumes:
        - ./rest-api/:/go/src/app
        - ~/.aws:/~/.aws