version: "3.2"
services:
  rest-api-demo:
    build:
        context: ./
        dockerfile: Dockerfile.dev
    environment:
      - ENVIRONMENT=dev
      - CHAOS_MONKEY_ENABLED=false
      - CHAOS_MONKEY_MODE=critical
      - CHAOS_MONKEY_LATENCY=false
      - CHAOS_MONKEY_EXCEPTION=false
      - CHAOS_MONKEY_APP_KILLER=false
      - CHAOS_MONKEY_MEMORY=false
    ports:
        - 8080:8080
    volumes:
        - ./:/go/src/rest-api-demo